### PR TITLE
feat: add get_wasmer_module function to wasmvm api and update cosmwasm

### PR DESCRIPTION
**Pull request by loloicci**
# Description
This PR adds `get_wasmer_module` to wasmvm. This is for interface validation of cosmwasm (https://github.com/line/cosmwasm/pull/245).

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [x] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/wasmvm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly. (not needed)
- [ ] I have added tests to cover my changes. (done in lbm-sdk)
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

**Review by zemyblue — COMMENTED** [review]
Could you add unittest?

**Comment by loloicci** [comment]
> Could you add unittest?

It is difficult to add unit tests for this change. This API is made from two parts, one is calling C (go) API, and another is calling `cosmwasm_vm::cache::get_module`. So we need 2 mocks to test this, and if we prepare them, we can test only deserializing of C API's returns. So, I test it in only the lbm-sdk's integration test.

**Comment by zemyblue** [comment]
> > Could you add unittest?
> 
> It is difficult to add unit tests for this change. This API is made from two parts, one is calling C (go) API, and another is calling `cosmwasm_vm::cache::get_module`. So we need 2 mocks to test this, and if we prepare them, we can test only deserializing of C API's returns. So, I test it in only the lbm-sdk's integration test.

If then, how can we check what is wrong?

**Comment by loloicci** [comment]
> If then, how can we check what is wrong?

OK..., I added tests for errors. Making cache mock takes too much time, so it is without sanity case.

**Review by shiki-tak — APPROVED** [review]
LGTM

**Review by zemyblue — APPROVED** [review]
I think it would be nice to apply codecov to this repository. Could you add this?

**Review by da1suk8 — APPROVED** [review]

**Comment by loloicci** [comment]
> I think it would be nice to apply codecov to this repository. Could you add this?

OK, I leave it to another issue. (casmwasm repository, too)

- https://github.com/line/wasmvm/issues/79
- https://github.com/line/cosmwasm/issues/249

**Pull request merged**
