### PR TITLE
ci: fix release action does not error if new tag pushing not needed

### PR DESCRIPTION
**Pull request by loloicci**
# Description
- version up rust
- the same as https://github.com/line/cosmwasm/pull/206.

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [ ] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/wasmvm/blob/main/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

**Review by shiki-tak — APPROVED** [review]
LGTM

**Comment by zemyblue** [comment]
I don't understand why the error is occurred? Could you explain this error?

**Comment by loloicci** [comment]
> I don't understand why the error is occurred. Could you explain this error?

- version up rust
  edition difference 2018 and 2021 causes an error.
- the same as https://github.com/line/cosmwasm/pull/206
  Previously, dudo/tag_check is used for checking if the newest tag differs from the version number. This tool supports only verifying that there is no diff between the newest tag and the version number. So, if there is no error, this issues an error. So the resting work (push tag) will be not done, but it looks like an error if there are no wrongs.

**Review by zemyblue — APPROVED** [review]

**Comment by zemyblue** [comment]
> @zemyblue
> 
> > I don't understand why the error is occurred. Could you explain this error?
> 
> * version up rust
>   edition difference 2018 and 2021 causes an error.
> * the same as [fix: release action ends with success even if it does not renew tag cosmwasm#206](https://github.com/line/cosmwasm/pull/206)
>   Previously, dudo/tag_check is used for checking if the newest tag differs from the version number. This tool supports only verifying that there is no diff between the newest tag and the version number. So, if there is no error, this issues an error. So the resting work (push tag) will be not done, but it looks like an error if there are no wrongs.

Now I understood. Thank you.

**Pull request merged**
